apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  labels:
    app: whateverx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whateverx
  template:
    metadata:
      labels:
        app: whateverx
    spec:
      containers:
      - name: whateverx-nginx
        image: nginx
        ports:
        - containerPort: 80